services:
  api:
    container_name: api_agrox
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agrodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: agro
      SPRING_DATASOURCE_PASSWORD: agro123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_agro
    restart: always
    environment:
      MYSQL_DATABASE: agrodb
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: agro
      MYSQL_PASSWORD: agro123
    ports:
      - "3307:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 3s
      timeout: 10s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
